### ISSUE TITLE
Request for Guidance 

### ISSUE THREAD

**Issue by HansJack1999** [zhanghefan123/LiR_Emulator#1]
Dear Zhang,
       I hope this message finds you well. I am a newcomer to the field of satellite technology, having started about a week ago, and I am currently unfamiliar with the various simulation software tools available. I am particularly interested in developing deep reinforcement learning-based satellite routing algorithms using these tools.
       I noticed from your profile that you have significant expertise and interest in this area. If possible, could you kindly share your contact information? I would greatly appreciate any guidance or advice you could provide.
       Thank you very much for your time and assistance.

Best regards,
Zhang Zhicheng
zhangzhicheng@iie.ac.cn

**Comment by zhanghefan123** [comment]
Dear Zhang Zhicheng,

Thank you for reaching out. It's exciting to hear about your interest in developing deep reinforcement learning-based satellite routing algorithms.

You can contact me by adding my wechat "ZHF200081".

Looking forward to our conversation.

Best regards,
Zhang





张贺凡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhanghefan123/LiR_Emulator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月2日(星期二) 中午11:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhanghefan123/LiR_Emulator] Request for Guidance  (Issue #1)





 
Dear Zhang,
 I hope this message finds you well. I am a newcomer to the field of satellite technology, having started about a week ago, and I am currently unfamiliar with the various simulation software tools available. I am particularly interested in developing deep reinforcement learning-based satellite routing algorithms using these tools.
 I noticed from your profile that you have significant expertise and interest in this area. If possible, could you kindly share your contact information? I would greatly appreciate any guidance or advice you could provide.
 Thank you very much for your time and assistance.
 
Best regards,
 Zhang Zhicheng
 ***@***.***
